
services:
  amplify-app:
    build: .
    container_name: amplify-app
    ports:
      - "5173:5173"
      - "3000:3000"
      - "4173:4173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=default
      - AWS_CONFIG_FILE=/root/.aws/config
    command: >
      sh -c "if [ \"$MODE\" = \"preview\" ]; then npm run preview; elif [ \"$MODE\" = \"build\" ]; then npm run build; else npm run dev; fi"
    # environment:
    #   - MODE=dev

